In [0]:
このデータは32×32×3のカラー画像で、10個のクラスから構成されています。
飛行機、自動車、鳥、猫、鹿、犬、カエル、ウマ、船、トラックの10個のクラスからなります。まずはそれを見てみます。

実はカラー画像の分類というのは、ディープラーニングを使わなくても従来の機械学習の手法でできます。
MNISTと同じように画像をベクトルにしてしまえばいいのです。減色操作をしてもいいですが、
しなくてもできます（しかも減色操作をしないほうがうまくいきます）。

例えばMNISTの場合、28×28×1（白黒なので1チャンネル）を784次元のベクトルとしました。
CIFAR-10の場合は32×32×3（RGBなので3チャンネル）を3072次元のベクトルとします。つまりベクトルを見ると、

[(0, 0)の赤], [(0, 1)の赤], ……, [(31, 31)の赤], [(0, 0)の緑], ……, [(31, 31)の緑], ……, [(31, 31)の青] 

In [1]:
# -*- coding: utf-8 -*-
#-*- coding: cp950 -*-
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from pathlib import Path
from typing import *

import torch
import torch.optim as optim

%reload_ext autoreload
%autoreload 2
%matplotlib inline

from fastai import *
from fastai.vision import *
from fastai.text import *
from fastai.callbacks import *
from fastai.core import *

import tensorflow as tf
import random as rn
np.random.seed(0)
rn.seed(0)

import keras
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
# Importing sklearn libraries
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
import pickle

from keras.preprocessing import image
from sklearn.model_selection import train_test_split

# Importing Keras libraries
from keras.utils import np_utils
from keras.models import Sequential
from keras.applications import VGG16
from keras.applications import imagenet_utils
from keras.callbacks import ModelCheckpoint
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.layers import Dense, Conv2D, MaxPooling2D
from keras.layers import Dropout, Flatten, GlobalAveragePooling2D
 
import warnings
warnings.filterwarnings('ignore')
import cv2

from keras.applications import ResNet50
from keras.datasets import cifar10

Using TensorFlow backend.


In [2]:
os.listdir()

['.config', 'sample_data']

In [3]:
#在colab下接入google drive
from google.colab import drive
drive.mount('/content/gdrive',force_remount = True)
base_dir = '/content/gdrive/My Drive'
#path = Path(base_dir +'/imgs4')  #imgs
path = Path(base_dir +'/DLtry')
path.mkdir(parents=True,exist_ok=True)
os.chdir(path)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [4]:
# データの読み込み
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
# 小数化
x_train = x_train / 255
x_test = x_test / 255

170500096/170498071 [==============================] - 2s 0us/step


In [5]:
# ロジスティック回帰
# データ数
m_train, m_test = x_train.shape[0], x_test.shape[0]

# ベクトル化
x_train, x_test = x_train.reshape(m_train, -1), x_test.reshape(m_test, -1)

# ノルムで標準化*******
x_train2 = x_train / np.linalg.norm(x_train, ord=2, axis=1, keepdims=True)
x_test2 = x_test / np.linalg.norm(x_test, ord=2, axis=1, keepdims=True)

import time
start_time = time.time()
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression()

logr.fit(x_train2, y_train)
print("Elapsed[s] : ", time.time() - start_time)
print("Train :", logr.score(x_train2, y_train))
print("Test :", logr.score(x_test2, y_test))

Elapsed[s] :  93.41054677963257
Train : 0.4171
Test : 0.4057


In [0]:
model=logr.fit(x_train2, y_train)
print(model.intercept_ )    #下列第一橫列
print(model.coef_) 

[-5.536812  6.177111 -2.328945  4.565471 -5.383747  1.766808 -1.933553  3.903827 -6.376968  5.146806]
[[ 0.170352  0.110942  0.982344  0.061879 ... -0.437402 -0.239735 -0.529524 -0.458354]
 [-0.135657 -0.470005 -0.585361  0.067784 ...  0.306831 -0.073056 -0.107496  0.312171]
 [ 0.089479  0.246642 -0.789732  0.282404 ... -0.344885  0.102758 -0.025665 -0.451987]
 [-0.055889 -0.653467 -0.851693  0.080396 ...  0.005711 -0.734209 -0.992213 -0.124824]
 ...
 [ 0.425854  0.274827 -0.631068  0.351925 ...  0.32477   0.430599  0.276689  0.385682]
 [-0.32784   0.15587   0.831972 -0.49632  ... -0.97884   1.002425  0.842056 -0.739654]
 [ 0.72591   0.620631  1.093757  0.564045 ...  0.943361 -1.527826 -0.264917  1.011463]
 [-0.127313  0.498678  1.301489 -0.324359 ...  0.777317  1.274991  0.645573  0.755904]]


In [0]:
pd.DataFrame(model.coef_)   #10個橫列,代表10種類別,用SVD或PCA來降維度

0         1         2     ...      3069      3070      3071
0  0.170352  0.110942  0.982344  ... -0.239735 -0.529524 -0.458354
1 -0.135657 -0.470005 -0.585361  ... -0.073056 -0.107496  0.312171
2  0.089479  0.246642 -0.789732  ...  0.102758 -0.025665 -0.451987
3 -0.055889 -0.653467 -0.851693  ... -0.734209 -0.992213 -0.124824
4 -0.581399 -0.557312 -0.694070  ...  0.118845  0.407418 -0.733165
5 -0.183496 -0.226806 -0.657636  ... -0.354792 -0.251921  0.042764
6  0.425854  0.274827 -0.631068  ...  0.430599  0.276689  0.385682
7 -0.327840  0.155870  0.831972  ...  1.002425  0.842056 -0.739654
8  0.725910  0.620631  1.093757  ... -1.527826 -0.264917  1.011463
9 -0.127313  0.498678  1.301489  ...  1.274991  0.645573  0.755904

[10 rows x 3072 columns]

In [6]:
#SVM 未標準化(有時優於有標準化)
from sklearn.svm import LinearSVC
svc = LinearSVC()

svc.fit(x_train2, y_train)
print("Elapsed[s] : ", time.time() - start_time)
print("Train :", svc.score(x_train2, y_train))
print("Test :", svc.score(x_test2, y_test))

Elapsed[s] :  845.5834405422211
Train : 0.45122
Test : 0.4062


In [0]:
#GB
from sklearn.ensemble import GradientBoostingClassifier
GB = GradientBoostingClassifier()

GB.fit(x_train2, y_train)
print("Elapsed[s] : ", time.time() - start_time)
print("Train :", GB.score(x_train2, y_train))
print("Test :", GB.score(x_test2, y_test))

In [0]:
#RF
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(x_train, y_train)
print("Elapsed[s] : ", time.time() - start_time)
print("Train :", rf.score(x_train, y_train))
print("Test :", rf.score(x_test, y_test))

Elapsed[s] :  421.99188804626465
Train : 1.0
Test : 0.4646


In [0]:
#設定max_depth,未必較佳
rf = RandomForestClassifier(max_depth=8)

rf.fit(x_train2, y_train)
print("Elapsed[s] : ", time.time() - start_time)
print("Train :", rf.score(x_train2, y_train))
print("Test :", rf.score(x_test2, y_test))

Elapsed[s] :  855.7198085784912
Train : 0.48894
Test : 0.4065


In [0]:
clf=rf.fit(x_train, y_train)
clf.feature_importances_

array([0.000295, 0.000296, 0.000444, 0.000286, ..., 0.000355, 0.000461, 0.000297, 0.00037 ])

In [0]:
pd.DataFrame(list(zip(x_train, clf.feature_importances_)))   #PCA,NMF

0         1
0     [0.23137254901960785, 0.24313725490196078, 0.2...  0.000295
1     [0.6039215686274509, 0.6941176470588235, 0.733...  0.000296
2     [1.0, 1.0, 1.0, 0.9921568627450981, 0.99215686...  0.000444
3     [0.10980392156862745, 0.09803921568627451, 0.0...  0.000286
4     [0.6666666666666666, 0.7058823529411765, 0.776...  0.000284
...                                                 ...       ...
3067  [0.5137254901960784, 0.16862745098039217, 0.29...  0.000342
3068  [0.6627450980392157, 0.7019607843137254, 0.749...  0.000355
3069  [0.5098039215686274, 0.11372549019607843, 0.05...  0.000461
3070  [0.21568627450980393, 0.2549019607843137, 0.22...  0.000297
3071  [0.3607843137254902, 0.5333333333333333, 0.709...  0.000370

[3072 rows x 2 columns]